# ANN

Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.2'

# Part 1: Data Preprocessing

Importing the dataset

In [ ]:
dataset=pd.read_csv('Churn_Modelling.csv')
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values


In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


Encoding Categorical data

Label encoding the gender column

In [ ]:
from  sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])   #X[:,2] will take all rows of index 2nd column

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot encoding the 'Geography' column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

Feature Scaling

In [ ]:
#feature scaling is absolutely compulsory for deep learning 
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


#Part 2: Building the ANN

Steps

*   Intialize the ANN as a sequence of layers
*   add the input layer and the first hidden layer composed of neurons
*   add the second hidden layer to build a deep learning model
*   add the output layer which will contain what we want to predict






Initialize the ANN

In [ ]:
ann=tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [ ]:
#fully connected layer will be created as an object of dense class
#units correspond to number of neurons we want to have in first hidden layer 
#input neurons will be features ie column name --> creditscore, gender,georgaphy...upto Estimated salary
#first input layer is created with some hidden neuron
# experiement with different no of neurons ( this is called hyperparameter) take units=6
#activation function of the hidden layers for fully connected layer will be rectifier function
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
#creates a first fully working connected hidden layer 


Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
#units=1 because we want the output neuron to have binary prediction 0 or 1 (leaves or stays in bank)
#sigmoid activation function in the output layer gives the binary probabilty of the outcome
#sigmoid gives probability of each customer whether it leaves the bank

# Training the ANN



*   Compiling the ANN using optimizer, loss function and metrics
*   Training the ANN on the training set over a certain number of epochs:



Compiling the ANN



*   good optimizer confirms to stochastic gradient descend. stochastic gradient: update the weights to reduce the loss between the predicted and real results, during training, at each iteration, we compare the prediction in the batch to the real results in the same batch, so stochastic gradient updates the weight
*   adam optimizer is the stochastic gradient descent, so next iteration, reduce the loss
*   loss - weight computed difference between the computed and real results
*  accuracy is the evaluation metric of our model. metrics that evaluate the ANN training 
*   classification when you have to predict binary outcome -->1]loss function is always 'binary_crossentropy'
*   for nonbinary classification predicting three different categories -->#1]loss function is 'categorical_crossentropy'  #2]activation must be sigmoid not softmax







In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

Training the ANN

In [ ]:
#batch training compares several real results to several predicted results in the batch.
#batch default size=32
#epoch is used to improve the accuracy over time 
ann.fit(X_train,y_train,batch_size=32,epochs=100)
#accuracy is averging around 0.86

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6606 - accuracy: 0.6181
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4972 - accuracy: 0.7951
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4542 - accuracy: 0.7991
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4390 - accuracy: 0.8056
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4318 - accuracy: 0.8091
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4262 - accuracy: 0.8138
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4191 - accuracy: 0.8196
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4099 - accuracy: 0.8250
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3994 - accuracy: 0.8299
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3904 - accura





# Making the predications and evaluating the result

Use our ANN model to predict if the customer with the following information will leave the bank

*   Geography : Finance
*   Credit Score : 600 
*   Gender : Male
*   Age : 40 years old 
*   Tenure : 3 years
*   Balance : $60000
*   Number of products : 2


*    Does this customer have a credit card ? Yes
*   Is this customer an Active Member : Yes


*   Estimated Salary : $50000
*   So, should we say goodbye to that customer?














In [ ]:
#enter the information we want to predict
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]




*   use the predict method to know that the customer with the following information will leave the bank.  
*    input to predict method will be 2D array double pair of square brackets. OneHotEncoder applied to geogrphy column leads to dummy vairable of FRANCE 1 0 0. Dummy variables are always created in the first column

*   predict method should be only applied to the type of observation on which training was done, scaling needs to be applied on the observation
*   sc object is used to perform scaled transformation on the entered dataset
*   transform method can be only applied on test set 


*  True -- customer leaves bank
*  False -- customer wont leave the bank









Predicting the test set results

In [ ]:
#display next to each other -- vector of prediction and vector of real results
#ann returns results in the form of probabilites
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5) 
#if y_pred between 0.5 and 1 value will be 1, because it is true
#if y_pred between 0 and 0.5 value will be 0
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))
#displays predications results and real results

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)
# received accuracy of 85 percent = 0.8585

[[1517   78]
 [ 205  200]]


0.8585